"""
Realistic load test for EMSG – derived from Session 646 (PMTA 2026, 85 users).

Session 646 profile
-------------------
Scenario : "Level 1 - Market mechanics" (scenario_id=15)
Cohort   : PMTA 2026 (cohort 182)
Rounds   : 3  |  horizon 3 h  |  span 1 h/round
Markets  : dam + idm
Player types:
  ptype_gen_a → dev_gen_a (2500 MW coal, 30 slots)
  ptype_gen_b → dev_gen_b (2500 MW coal, 23 slots)
  ptype_gen_c → dev_gen_c (2500 MW coal, 21 slots)
Observed S646 activity:
  session_join×83, type_select×74, forecast_submit×200, round_complete×170

User mix
--------
PlayerUser  weight=82  – student/participant
AdminUser   weight=3   – trainer monitoring the session

Write mode (EMSG_ALLOW_WRITES=1)
---------------------------------
PlayerUser performs the full round lifecycle per VU:
  login → discover session → select player type (once) →
  poll round status → submit forecast per round → view results

Without EMSG_ALLOW_WRITES (default) all write tasks are skipped and the
test stays read-only, suitable for smoke-testing a production instance.

Credentials
-----------
Priority:
  1. EMSG_USERS_CSV  path to CSV with columns: email,password,role,user_id
     (generated by backend/tests/perf/setup_loadtest_session.py)
  2. EMSG_EMAIL + EMSG_PASSWORD  (single account, replicated for all VUs)

Environment variables
---------------------
  EMSG_ALLOW_WRITES=1       Enable forecast submissions and type selection
  EMSG_SESSION_ID=N         Force a specific session (AdminUser uses this)
  EMSG_COHORT_ID=N          Cohort for AdminUser monitoring endpoints
  EMSG_USERS_CSV=path       CSV credentials file
  EMSG_EMAIL / EMSG_PASSWORD  Fallback single-account credentials

Quick start (load test against the live backend after setup)
------------------------------------------------------------
  # 1. Provision test session
  docker cp backend/tests/perf/setup_loadtest_session.py emsg-backend-1:/tmp/
  docker exec emsg-backend-1 python3 /tmp/setup_loadtest_session.py

  # 2. Run locust (copy the docker run command printed by the setup script)
  EMSG_SESSION_ID=... EMSG_COHORT_ID=... EMSG_USERS_CSV=/tmp/loadtest_users.csv \\
  docker run --rm \\
    -v "$PWD/backend/tests/perf/locustfile.py:/locustfile.py:ro" \\
    -v "/tmp/loadtest_users.csv:/tmp/loadtest_users.csv:ro" \\
    --network host \\
    -e EMSG_SESSION_ID=$EMSG_SESSION_ID \\
    -e EMSG_COHORT_ID=$EMSG_COHORT_ID \\
    -e EMSG_USERS_CSV=/tmp/loadtest_users.csv \\
    -e EMSG_ALLOW_WRITES=1 \\
    locustio/locust:latest \\
    -f /locustfile.py --host=http://localhost:15000 \\
    -u 85 -r 8 --run-time=390s --headless
"""
from __future__ import annotations

import csv
import itertools
import os
import random
import threading

from locust import HttpUser, between, events, task

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
_ALLOW_WRITES: bool = os.getenv("EMSG_ALLOW_WRITES", "0").strip() in ("1", "true", "yes")
# Optional override: skip the active-session discovery and use this session directly.
# Set by setup_loadtest_session.py; leave unset to auto-discover.
_FORCED_SESSION_ID: int | None = int(os.getenv("EMSG_SESSION_ID", "0")) or None
_FORCED_COHORT_ID: int | None = int(os.getenv("EMSG_COHORT_ID", "0")) or None

# Scenario 15 / Load Test scenario constants
_ROUNDS: int = 3
_PLAYER_TYPES: list[dict] = [
    {"type_id": "ptype_gen_a", "device_id": "dev_gen_a", "capacity_mw": 2500.0},
    {"type_id": "ptype_gen_b", "device_id": "dev_gen_b", "capacity_mw": 2500.0},
    {"type_id": "ptype_gen_c", "device_id": "dev_gen_c", "capacity_mw": 2500.0},
]
# Weighted to match observed slot distribution 30 : 23 : 21
_PLAYER_TYPE_WEIGHTS: list[int] = [30, 23, 21]

# ---------------------------------------------------------------------------
# Credential pool – shared, thread-safe round-robin across all VUs
# ---------------------------------------------------------------------------
_player_creds: list[tuple[str, str]] = []
_trainer_creds: list[tuple[str, str]] = []
_player_cycle: itertools.cycle | None = None
_trainer_cycle: itertools.cycle | None = None
_creds_lock = threading.Lock()


def _load_credentials() -> None:
    global _player_cycle, _trainer_cycle

    csv_path = os.getenv("EMSG_USERS_CSV", "")
    if csv_path and os.path.exists(csv_path):
        with open(csv_path, newline="") as fh:
            for row in csv.DictReader(fh):
                email = (row.get("email") or "").strip()
                password = (row.get("password") or "").strip()
                role = (row.get("role") or "player").strip().lower()
                if not email or not password:
                    continue
                if role in ("trainer", "admin"):
                    _trainer_creds.append((email, password))
                else:
                    _player_creds.append((email, password))

    if not _player_creds and not _trainer_creds:
        email = os.getenv("EMSG_EMAIL", "")
        password = os.getenv("EMSG_PASSWORD", "")
        if email and password:
            for _ in range(100):
                _player_creds.append((email, password))
            _trainer_creds.append((email, password))

    if _player_creds:
        _player_cycle = itertools.cycle(_player_creds)
    if _trainer_creds:
        _trainer_cycle = itertools.cycle(_trainer_creds)


def _next_player_creds() -> tuple[str, str] | None:
    if _player_cycle is None:
        return None
    with _creds_lock:
        return next(_player_cycle)


def _next_trainer_creds() -> tuple[str, str] | None:
    if _trainer_cycle is None:
        # Fall back to player credentials if no trainers are available
        return _next_player_creds()
    with _creds_lock:
        return next(_trainer_cycle)


@events.init.add_listener
def on_locust_init(environment, **_kw):
    _load_credentials()
    if not _player_creds and not _trainer_creds:
        raise SystemExit(
            "No credentials found.\n"
            "  Option A: Set EMSG_EMAIL + EMSG_PASSWORD\n"
            "  Option B: Set EMSG_USERS_CSV to a CSV with email,password,role columns\n"
            "            (run backend/tests/perf/setup_loadtest_session.py first)"
        )
    print(
        f"[locust] Credentials loaded: {len(_player_creds)} player, {len(_trainer_creds)} trainer | "
        f"writes={'ON' if _ALLOW_WRITES else 'OFF'} | "
        f"forced_session={_FORCED_SESSION_ID}",
        flush=True,
    )


# ---------------------------------------------------------------------------
# Base class
# ---------------------------------------------------------------------------

class _BaseEMSGUser(HttpUser):
    abstract = True
    token: str | None = None
    _auth_headers: dict

    def on_start(self) -> None:
        self._auth_headers = {}
        creds = self._pick_credentials()
        if creds is None:
            return
        email, password = creds
        with self.client.post(
            "/api/auth/login",
            json={"email": email, "password": password},
            catch_response=True,
            name="POST /api/auth/login",
        ) as resp:
            if resp.status_code == 200:
                body = resp.json()
                self.token = body.get("access_token")
                if self.token:
                    self._auth_headers = {"Authorization": f"Bearer {self.token}"}
                resp.success()
            else:
                resp.failure(f"Login failed for {email}: {resp.status_code}")

    def _pick_credentials(self) -> tuple[str, str] | None:
        return _next_player_creds()

    def _get(self, url: str, name: str | None = None, **kwargs):
        return self.client.get(url, headers=self._auth_headers, name=name or url, **kwargs)

    def _post(self, url: str, payload: dict, name: str | None = None, **kwargs):
        return self.client.post(
            url, json=payload, headers=self._auth_headers, name=name or url, **kwargs
        )


# ---------------------------------------------------------------------------
# PlayerUser  (weight=82)
#
# Full lifecycle with writes:
#   login → discover session → select type (once per session) →
#   heavy status polling → submit forecast when round advances →
#   view results / leaderboard after each round
#
# Task-weight rationale derived from S646 activity log + SPA polling patterns:
#   - status/active-session polls dominate (SPA fires every 2-4s)
#   - market-timeline + structure: once per round phase
#   - forecast submit: ~0.8×/round/player → weight 5, gated by round state
#   - results/leaderboard: once per round completion
# ---------------------------------------------------------------------------

class PlayerUser(_BaseEMSGUser):
    """Simulates a student player in the PMTA 2026 cohort (session 646 profile)."""

    wait_time = between(2, 8)
    weight = 82

    def on_start(self) -> None:
        # Per-VU mutable state – all initialised here (never as class attributes)
        self._session_id: int | None = _FORCED_SESSION_ID
        self._current_round: int = 1
        self._last_forecast_round: int = 0   # round for which we last submitted
        self._type_selected: bool = False
        self._player_type: dict = random.choices(
            _PLAYER_TYPES, weights=_PLAYER_TYPE_WEIGHTS, k=1
        )[0]

        super().on_start()
        if not self.token:
            return

        # Initial session discovery
        with self.client.get(
            "/api/player/active-session",
            headers=self._auth_headers,
            name="GET /api/player/active-session",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                data = resp.json()
                if data.get("session_id"):
                    self._session_id = data["session_id"]
                    self._current_round = int(data.get("round") or 1)
                resp.success()
            else:
                resp.success()  # No session is valid (session not started yet)

    # ------------------------------------------------------------------ polling

    @task(15)
    def poll_active_session(self):
        """SPA polls this every few seconds to detect session start + round changes."""
        with self.client.get(
            "/api/player/active-session",
            headers=self._auth_headers,
            name="GET /api/player/active-session",
            catch_response=True,
        ) as resp:
            if resp.status_code == 200:
                data = resp.json()
                if data.get("session_id"):
                    if not self._session_id:
                        self._session_id = data["session_id"]
                    new_round = int(data.get("round") or 1)
                    if new_round != self._current_round:
                        self._current_round = new_round
                        # New round → reset type_selected flag so we re-confirm it
                        # (type selection is idempotent, but the flag avoids re-calls
                        #  when the type is already set in DB)
                resp.success()
            elif resp.status_code == 401:
                resp.failure("Unauthenticated")
            else:
                resp.success()

    @task(12)
    def poll_submit_status(self):
        """Players poll submit-status to see who has submitted in the waiting screen."""
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}/submit-status",
            name="GET /api/sessions/<sid>/submit-status",
        )

    # ------------------------------------------------------------------ round gameplay

    @task(8)
    def get_market_timeline(self):
        """Loaded once when entering a new round phase."""
        if not self._session_id:
            return
        self._get(
            f"/api/player/market-timeline/{self._session_id}/{self._current_round}",
            name="GET /api/player/market-timeline/<sid>/<round>",
        )

    @task(6)
    def get_market_structure(self):
        """Loaded per-hour to show supply/demand curves (1 hour per round in S646)."""
        if not self._session_id:
            return
        hour = self._current_round - 1   # 0-based horizon index for span=1h
        self._get(
            f"/api/player/market-structure/{self._session_id}/{self._current_round}/{hour}",
            name="GET /api/player/market-structure/<sid>/<round>/<hour>",
        )

    @task(5)
    def get_da_baseline(self):
        """Fetched at the start of each round to pre-fill the forecast form."""
        if not self._session_id:
            return
        self._get(
            f"/api/player/da-baseline/{self._session_id}",
            name="GET /api/player/da-baseline/<sid>",
        )

    @task(5)
    def submit_forecast(self):
        """
        Core write task – submits a forecast for the current round.

        Gating rules (mirrors S646 observed patterns):
          - Skipped entirely unless EMSG_ALLOW_WRITES=1
          - Skipped if no session is known yet
          - Skipped if we already submitted for this round
          - Includes type selection on first call (idempotent)
        """
        if not _ALLOW_WRITES or not self._session_id:
            return
        if self._current_round <= self._last_forecast_round:
            return  # Already submitted for this round; wait for next round

        # Select player type once (idempotent – server returns 200 if already set)
        if not self._type_selected:
            with self.client.post(
                f"/api/sessions/{self._session_id}/select-type",
                json={"type_id": self._player_type["type_id"]},
                headers=self._auth_headers,
                name="POST /api/sessions/<sid>/select-type",
                catch_response=True,
            ) as resp:
                if resp.status_code in (200, 201):
                    self._type_selected = True
                    resp.success()
                elif resp.status_code == 409:
                    # Type capacity reached – pick a different type
                    self._player_type = random.choice(_PLAYER_TYPES)
                    resp.success()
                else:
                    resp.failure(f"select-type {resp.status_code}")
                    return   # Don't submit forecast if type selection failed

        # Build realistic forecast payload (40–95 % of device capacity)
        pt = self._player_type
        mw = round(random.uniform(0.40, 0.95) * pt["capacity_mw"], 2)
        payload = {
            "session_id": self._session_id,
            "round_num": self._current_round,
            "hours": [mw],
            "devices": [{"device_id": pt["device_id"], "hours": [mw]}],
        }

        with self.client.post(
            "/api/player/forecast",
            json=payload,
            headers=self._auth_headers,
            name="POST /api/player/forecast",
            catch_response=True,
        ) as resp:
            if resp.status_code in (200, 201):
                self._last_forecast_round = self._current_round
                resp.success()
            elif resp.status_code == 400:
                # Gate closure violation or validation error – expected occasionally
                resp.success()
            else:
                resp.failure(f"forecast {resp.status_code}: {resp.text[:80]}")

    # ------------------------------------------------------------------ results / leaderboard

    @task(8)
    def view_session_overview(self):
        """Players check their session page after each round."""
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}",
            name="GET /api/sessions/<sid>",
        )

    @task(7)
    def view_leaderboard(self):
        """Fetched after every round completion (170 round_complete events in S646)."""
        if not self._session_id:
            return
        self._get(
            f"/api/leaderboard/sessions/{self._session_id}",
            name="GET /api/leaderboard/sessions/<sid>",
        )

    @task(5)
    def view_round_results(self):
        """Results detail page – opened after round ends."""
        if not self._session_id or self._last_forecast_round < 1:
            return
        rnd = max(1, self._last_forecast_round)
        self._get(
            f"/api/sessions/{self._session_id}/round-results/{rnd}",
            name="GET /api/sessions/<sid>/round-results/<round>",
        )

    @task(4)
    def view_briefing(self):
        """Scenario briefing – fetched once per session, re-fetched on browser refresh."""
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}/briefing",
            name="GET /api/sessions/<sid>/briefing",
        )

    # ------------------------------------------------------------------ navigation / account

    @task(4)
    def navigate(self):
        """SPA navigation helper – called on every hard reload."""
        self._get("/api/me/navigate", name="GET /api/me/navigate")

    @task(3)
    def my_sessions(self):
        self._get("/api/me/sessions", name="GET /api/me/sessions")

    @task(2)
    def my_profile(self):
        self._get("/api/me/profile", name="GET /api/me/profile")

    @task(1)
    def health(self):
        self.client.get("/api/health", name="GET /api/health")


# ---------------------------------------------------------------------------
# AdminUser  (weight=3)
#
# Simulates a trainer monitoring the session dashboard.
# Heavy polling on presence, participants, and submission status.
# Does NOT advance rounds (the server timer handles that automatically).
# ---------------------------------------------------------------------------

class AdminUser(_BaseEMSGUser):
    """Simulates a trainer/admin from the PMTA 2026 cohort (3 admins observed in S646)."""

    wait_time = between(4, 12)
    weight = 3

    def _pick_credentials(self) -> tuple[str, str] | None:
        return _next_trainer_creds()

    def on_start(self) -> None:
        self._session_id: int | None = _FORCED_SESSION_ID
        self._cohort_id: int | None = _FORCED_COHORT_ID

        super().on_start()
        if not self.token:
            return

        # Discover active session if not forced
        if not self._session_id and self._cohort_id:
            with self.client.get(
                f"/api/sessions/active?cohort_id={self._cohort_id}",
                headers=self._auth_headers,
                name="GET /api/sessions/active",
                catch_response=True,
            ) as resp:
                if resp.status_code == 200:
                    data = resp.json()
                    self._session_id = data.get("id") or data.get("session_id")
                    resp.success()
                else:
                    resp.success()

    # ------------------------------------------------------------------ monitoring

    @task(12)
    def poll_presence(self):
        """Trainer dashboard polls presence to show online-player count."""
        self._get("/api/trainer/presence", name="GET /api/trainer/presence")

    @task(10)
    def poll_session_status(self):
        """Submission-status matrix for all players."""
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}/status",
            name="GET /api/sessions/<sid>/status [admin]",
        )

    @task(8)
    def view_session_participants(self):
        """Participant list – who's online and what type they picked."""
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}/participants",
            name="GET /api/sessions/<sid>/participants",
        )

    @task(7)
    def view_session_overview(self):
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}",
            name="GET /api/sessions/<sid> [admin]",
        )

    @task(5)
    def get_cohort_members(self):
        if not self._cohort_id:
            return
        self._get(
            f"/api/trainer/cohort/{self._cohort_id}/members",
            name="GET /api/trainer/cohort/<id>/members",
        )

    @task(5)
    def list_active_sessions(self):
        if self._cohort_id:
            self._get(
                f"/api/sessions/active?cohort_id={self._cohort_id}",
                name="GET /api/sessions/active",
            )
        else:
            self._get("/api/sessions/active", name="GET /api/sessions/active")

    @task(4)
    def view_round_results(self):
        if not self._session_id:
            return
        self._get(
            f"/api/sessions/{self._session_id}/round-results/1",
            name="GET /api/sessions/<sid>/round-results/<round> [admin]",
        )

    @task(3)
    def view_leaderboard(self):
        if not self._session_id:
            return
        self._get(
            f"/api/leaderboard/sessions/{self._session_id}",
            name="GET /api/leaderboard/sessions/<sid> [admin]",
        )

    @task(2)
    def health(self):
        self.client.get("/api/health", name="GET /api/health")
