"""
Integration tests for device model in Engine and Player
"""
import pytest
from app.engine import apply_grid, run_round
from app.device_types import DeviceType


class TestEngineCurtailmentPriority:
    """Test engine curtailment with device priorities"""
    
    def test_apply_grid_with_devices_sorted_by_priority(self):
        """Devices should be sorted by priority before curtailment"""
        devices = [
            {'type': 'NUCLEAR', 'max_power_mw': 900},  # Priority 4 (last)
            {'type': 'SOLAR', 'max_power_mw': 200},    # Priority 1 (first)
            {'type': 'COAL', 'max_power_mw': 500},     # Priority 3
            {'type': 'GAS', 'max_power_mw': 200},      # Priority 2
        ]
        
        volume = 10000  # MW
        atc = [[0, 5000], [5000, 0]]  # ATC cap will cause curtailment
        
        curtailed, cong_signal = apply_grid(volume, atc, devices=devices)
        
        # Should return curtailment amount and congestion signal
        assert curtailed > 0
        assert 0 <= cong_signal <= 1
    
    def test_apply_grid_without_devices(self):
        """apply_grid should work without devices (backward compatibility)"""
        volume = 10000
        atc = [[0, 5000], [5000, 0]]
        
        curtailed, cong_signal = apply_grid(volume, atc)
        
        assert curtailed > 0
        assert 0 <= cong_signal <= 1
    
    def test_apply_grid_no_curtailment_needed(self):
        """No curtailment when volume is within ATC capacity"""
        devices = [
            {'type': 'COAL', 'max_power_mw': 500},
        ]
        
        volume = 5000  # Below ATC capacity
        atc = [[0, 10000], [10000, 0]]
        
        curtailed, cong_signal = apply_grid(volume, atc, devices=devices)
        
        assert curtailed == 0
        assert cong_signal == 0
    
    def test_apply_grid_empty_devices_list(self):
        """Empty devices list should not cause errors"""
        volume = 10000
        atc = [[0, 5000], [5000, 0]]
        devices = []
        
        curtailed, cong_signal = apply_grid(volume, atc, devices=devices)
        
        assert curtailed > 0
        assert 0 <= cong_signal <= 1


class TestEngineRunRoundWithDevices:
    """Test run_round with device-enhanced config"""
    
    def test_run_round_with_devices_in_config(self):
        """run_round should pass devices to apply_grid"""
        config = {
            "general": {"round_span_hours": 6, "horizon_hours": 24, "rounds": 4},
            "market": {"base_price": 1000, "base_volume_mwh": 20000, "price_floor": -500, "price_cap": 5000},
            "grid": {"zones": 2, "atc": [[0, 5000], [5000, 0]]},
            "devices": [
                {"type": "COAL", "max_power_mw": 500, "min_load_pct": 40, "ramp_rate_mw_per_min": 5, "cost_zar_per_mwh": 400},
                {"type": "SOLAR", "max_power_mw": 200, "capacity_factor": 0.25},
            ],
            "events": []
        }
        
        players = [1, 2]
        forecasts = {
            1: [100] * 24,  # 24 hours forecast
            2: [150] * 24
        }
        
        result = run_round(
            session_id=1,
            round_num=1,
            players=players,
            forecasts=forecasts,
            config=config,
            mode="isolated_per_player"
        )
        
        # Should complete without errors
        assert "smp" in result
        assert "volume" in result
        assert "round_kpis" in result
        assert 1 in result["round_kpis"]
        assert 2 in result["round_kpis"]
    
    def test_run_round_shared_market_with_devices(self):
        """run_round in shared_market mode with devices"""
        config = {
            "general": {"round_span_hours": 6, "horizon_hours": 24, "rounds": 4},
            "market": {"base_price": 1000, "base_volume_mwh": 20000, "price_floor": -500, "price_cap": 5000},
            "grid": {"zones": 2, "atc": [[0, 5000], [5000, 0]]},
            "devices": [
                {"type": "NUCLEAR", "max_power_mw": 900, "min_load_pct": 90, "ramp_rate_mw_per_min": 1, "cost_zar_per_mwh": 100},
                {"type": "WIND", "max_power_mw": 150, "capacity_factor": 0.35},
            ],
            "events": []
        }
        
        players = [1, 2, 3]
        forecasts = {
            1: [200] * 24,
            2: [300] * 24,
            3: [250] * 24
        }
        
        result = run_round(
            session_id=1,
            round_num=1,
            players=players,
            forecasts=forecasts,
            config=config,
            mode="shared_market"
        )
        
        assert "smp" in result
        assert "volume" in result
        assert len(result["round_kpis"]) == 3

    def test_run_round_reports_battery_kpis_from_device_breakdown(self):
        """Battery KPIs should reconcile with the per-device settlement rows generated by run_round."""
        config = {
            "general": {
                "round_span_hours": 2,
                "horizon_hours": 24,
                "rounds": 4,
                "start_time": "00:00",
                "fake_date": "2025-01-01",
            },
            "market": {
                "enable_player_bidding": True,
                "base_price": 1000,
                "base_volume_mwh": 20000,
                "price_floor": -500,
                "price_cap": 5000,
            },
            "grid": {"zones": 2, "atc": [[0, 5000], [5000, 0]]},
            "devices": [
                {
                    "id": "bat_1",
                    "type": "battery",
                    "owner_id": 1,
                    "capacity_mwh": 100,
                    "power_mw": 20,
                    "efficiency_pct": 85,
                    "initial_soc_pct": 50,
                    "max_dod_pct": 80,
                }
            ],
            "events": [],
        }

        charge_hours = [-20.0, 0.0] + [0.0] * 22
        discharge_hours = [0.0, 20.0] + [0.0] * 22
        forecasts = {
            1: {
                "hours": [0.0] * 24,
                "devices": [{"device_id": "bat_1"}],
                "bids": {
                    "bat_1": {
                        "A": {"price": 5000, "hours": charge_hours},
                        "B": {"price": 0, "hours": discharge_hours},
                    }
                },
            }
        }

        result = run_round(
            session_id=1,
            round_num=1,
            players=[1],
            forecasts=forecasts,
            config=config,
            mode="isolated_per_player",
            seed="battery-kpi-test",
        )

        kpis = result["round_kpis"][1]
        device_rows = kpis["device_hourly_breakdown"]["bat_1"]

        assert len(device_rows) == 2
        assert kpis["battery_soc_start_pct"] == pytest.approx(50.0)
        assert kpis["battery_soc_end_pct"] is not None
        assert 20.0 <= kpis["battery_soc_end_pct"] <= 100.0
        assert kpis["battery_charged_mwh"] > 0.0
        assert kpis["battery_discharged_mwh"] > 0.0

        charged_total = sum(float(row.get("battery_charged_mwh", 0.0) or 0.0) for row in device_rows)
        discharged_total = sum(float(row.get("total_dispatched_mwh", 0.0) or 0.0) for row in device_rows)
        charge_cost_total = sum(float(row.get("battery_charge_cost_zar", 0.0) or 0.0) for row in device_rows)
        discharge_revenue_total = sum(
            float(row.get("da_revenue_zar", 0.0) or 0.0) + float(row.get("id_revenue_zar", 0.0) or 0.0)
            for row in device_rows
        )

        assert kpis["battery_charged_mwh"] == pytest.approx(charged_total, abs=1e-3)
        assert kpis["battery_discharged_mwh"] == pytest.approx(discharged_total, abs=1e-3)
        assert kpis["battery_charge_cost_zar"] == pytest.approx(charge_cost_total, abs=1e-2)
        assert kpis["battery_arbitrage_revenue_zar"] == round(discharge_revenue_total - charge_cost_total, 0)

    def test_classic_producer_bid_count_zero_keeps_co2_when_bidding_enabled(self):
        """A classic producer (bid_count=0) must still produce non-zero CO2 when dispatched."""
        config = {
            "general": {
                "round_span_hours": 2,
                "horizon_hours": 24,
                "rounds": 2,
                "start_time": "00:00",
                "fake_date": "2025-01-01",
            },
            "market": {
                "enable_player_bidding": False,
                "base_price": 1000,
                "base_volume_mwh": 200,
                "price_floor": -500,
                "price_cap": 5000,
            },
            "grid": {"zones": 1, "atc": [[0]]},
            "devices": [
                {
                    "id": "coal_1",
                    "type": "coal",
                    "owner_id": 1,
                    "bid_count": 0,
                    "max_power_mw": 200,
                    "variable_cost_tiers": [
                        {"from_pct": 0, "to_pct": 60, "cost_zar_per_mwh": 380},
                        {"from_pct": 60, "to_pct": 90, "cost_zar_per_mwh": 440},
                        {"from_pct": 90, "to_pct": 100, "cost_zar_per_mwh": 520},
                    ],
                },
                {
                    # Forces explicit-bids mode globally, while coal_1 still uses classic fallback.
                    "id": "gas_toggle",
                    "type": "gas",
                    "owner_id": 1,
                    "bid_count": 1,
                    "max_power_mw": 50,
                    "variable_cost_zar_per_mwh": 1200,
                },
            ],
            "events": [],
        }

        forecasts = {
            1: {
                "hours": [0.0] * 24,
                "devices": [
                    {"device_id": "coal_1", "hours": [80.0] * 24},
                ],
                "bids": {
                    "coal_1": {},
                },
            }
        }

        result = run_round(
            session_id=1,
            round_num=1,
            players=[1],
            forecasts=forecasts,
            config=config,
            mode="isolated_per_player",
            seed="classic-bidcount-zero-co2",
        )

        kpis = result["round_kpis"][1]
        # dispatched and planned must both be non-zero: bid_count=0 reads hours from devices array
        assert kpis["dispatched_mwh"] > 0.0
        assert kpis["planned_mwh"] > 0.0, "bid_count=0: planned_mwh must come from devices[].hours"
        assert kpis["co2_emissions_kg"] > 0.0

        coal_rows = kpis["device_hourly_breakdown"]["coal_1"]
        assert sum(float(row.get("dispatched_mw", 0.0) or 0.0) for row in coal_rows) > 0.0
        assert sum(float(row.get("planned_mw", 0.0) or 0.0) for row in coal_rows) > 0.0, \
            "bid_count=0: per-device planned_mw must be populated from forecast hours"
        assert sum(float(row.get("co2_kg", 0.0) or 0.0) for row in coal_rows) > 0.0


class TestPlayerForecastValidation:
    """Test player forecast validation against device constraints
    
    Note: These tests would require a Flask app context and database setup.
    Marking as integration tests that need proper test fixtures.
    """
    
    def test_forecast_validation_min_load_violation(self):
        """Forecast below min_load should be rejected"""
        # This would require Flask app context and DB
        # Placeholder for future implementation
        pass
    
    def test_forecast_validation_ramp_rate_violation(self):
        """Forecast exceeding ramp_rate should be rejected"""
        # This would require Flask app context and DB
        # Placeholder for future implementation
        pass
    
    def test_forecast_validation_success(self):
        """Valid forecast should be accepted"""
        # This would require Flask app context and DB
        # Placeholder for future implementation
        pass


class TestDeviceIntegrationWorkflow:
    """End-to-end workflow tests for device integration"""
    
    def test_complete_workflow_coal_portfolio(self):
        """Complete workflow: Coal device, forecast validation, engine curtailment"""
        # Config with Coal device
        config = {
            "general": {"round_span_hours": 6, "horizon_hours": 24, "rounds": 4},
            "market": {"base_price": 1000, "base_volume_mwh": 20000},
            "grid": {"zones": 2, "atc": [[0, 5000], [5000, 0]]},
            "devices": [
                {
                    "type": "COAL",
                    "max_power_mw": 500,
                    "min_load_pct": 40,  # 200 MW minimum
                    "ramp_rate_mw_per_min": 5,  # 300 MW/hour
                    "cost_zar_per_mwh": 400
                }
            ],
            "events": []
        }
        
        # Valid forecast (respects min_load and ramp_rate)
        forecast = [250] * 24  # All hours >= 200 MW
        
        # Run round
        result = run_round(
            session_id=1,
            round_num=1,
            players=[1],
            forecasts={1: forecast},
            config=config,
            mode="isolated_per_player"
        )
        
        assert result["round_kpis"][1]["planned_mwh"] == 250 * 6  # 6 hours
    
    def test_complete_workflow_mixed_portfolio(self):
        """Mixed portfolio: Nuclear (base load) + Solar (intermittent)"""
        config = {
            "general": {"round_span_hours": 6, "horizon_hours": 24, "rounds": 4},
            "market": {"base_price": 1000, "base_volume_mwh": 25000},
            "grid": {"zones": 2, "atc": [[0, 8000], [8000, 0]]},
            "devices": [
                {
                    "type": "NUCLEAR",
                    "max_power_mw": 900,
                    "min_load_pct": 90,  # 810 MW minimum (base load)
                    "ramp_rate_mw_per_min": 1,  # 60 MW/hour (slow ramp)
                    "cost_zar_per_mwh": 100
                },
                {
                    "type": "SOLAR",
                    "max_power_mw": 200,
                    "capacity_factor": 0.25  # No min_load/ramp constraints
                }
            ],
            "events": []
        }
        
        forecast_nuclear = [850] * 24  # Steady base load
        forecast_solar = [50, 100, 150, 200, 150, 100] * 4  # Variable (OK for solar)
        
        result = run_round(
            session_id=1,
            round_num=1,
            players=[1, 2],
            forecasts={
                1: forecast_nuclear,
                2: forecast_solar
            },
            config=config,
            mode="shared_market"
        )
        
        assert "smp" in result
        assert 1 in result["round_kpis"]
        assert 2 in result["round_kpis"]
    
    def test_curtailment_priority_order(self):
        """Curtailment should follow priority: Solar first, Nuclear last"""
        config = {
            "general": {"round_span_hours": 6, "horizon_hours": 24, "rounds": 4},
            "market": {"base_price": 1000, "base_volume_mwh": 10000},  # Low volume → curtailment
            "grid": {"zones": 2, "atc": [[0, 3000], [3000, 0]]},  # Low ATC → more curtailment
            "devices": [
                {"type": "SOLAR", "max_power_mw": 200},     # Priority 1 (curtail first)
                {"type": "GAS", "max_power_mw": 200},       # Priority 2
                {"type": "COAL", "max_power_mw": 500},      # Priority 3
                {"type": "NUCLEAR", "max_power_mw": 900},   # Priority 4 (curtail last)
            ],
            "events": []
        }
        
        # All devices forecast high output
        forecast = [300] * 24  # Total planned > available capacity
        
        result = run_round(
            session_id=1,
            round_num=1,
            players=[1, 2, 3, 4],
            forecasts={
                1: forecast,  # Solar
                2: forecast,  # Gas
                3: forecast,  # Coal
                4: forecast,  # Nuclear
            },
            config=config,
            mode="shared_market"
        )
        
        # All players should have curtailment costs due to capacity limits
        for player_id in [1, 2, 3, 4]:
            kpis = result["round_kpis"][player_id]
            # In shared_market, dispatch_factor < 1 → curtailment_amount > 0
            assert kpis["planned_mwh"] >= kpis["dispatched_mwh"]
