#!/usr/bin/env python3
"""Compare curves generated by backend vs KSE frontend logic"""
import sys
sys.path.insert(0, '/home/ga/energy-game/backend')

from app.engine import generate_curves_from_config

# Test config matching typical KSE setup
cfg = {
    "market": {
        "base_price": 1000,
        "base_volume_mwh": 20000,
        "price_floor": -500,
        "price_cap": 5000,
        "random_capacity_pct": 10,
        "random_price_pct": 5,
        "generator_mix": {
            "pv": 250,
            "wind": 200,
            "hydro": 100,
            "coal": 300,
            "gas": 150
        },
        "consumer_mix": {
            "industrial": 400,
            "household": 500,
            "agriculture": 100
        }
    },
    "environment": {
        "seed": "test123"
    }
}

supply, demand = generate_curves_from_config(cfg, seed="test123", hour_of_day=12, month_of_year=6)

print(f"Supply blocks: {len(supply)}")
print(f"Demand blocks: {len(demand)}")
print(f"\nFirst 5 supply blocks:")
for i, (p, q) in enumerate(supply[:5]):
    print(f"  {i+1}. Price: {p:.2f}, Volume: {q:.2f}")

print(f"\nFirst 5 demand blocks:")
for i, (p, q) in enumerate(demand[:5]):
    print(f"  {i+1}. Price: {p:.2f}, Volume: {q:.2f}")

print(f"\nSupply total volume: {sum(q for p,q in supply):.2f}")
print(f"Demand total volume: {sum(q for p,q in demand):.2f}")

# Check type distribution
print(f"\nGenerator mix total blocks: {250+200+100+300+150} = 1000")
print(f"Consumer mix total blocks: {400+500+100} = 1000")
