import io
import os
from flask import send_file, jsonify
from flask_restx import Namespace, Resource
from flask_jwt_extended import jwt_required

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle

from .extensions import db
from .models import Session, Scenario, Result


ns = Namespace("export", description="Export JSON/PDF")


@ns.route("/sessions/<int:sid>/json")
class ExportJSON(Resource):
    @jwt_required()
    def get(self, sid: int):
        s = Session.query.get_or_404(sid)
        sc = Scenario.query.get(s.scenario_id)
        results = [
            {"player_id": r.player_id, "round": r.round_num, **(r.data or {})}
            for r in Result.query.filter_by(session_id=sid).order_by(Result.player_id, Result.round_num).all()
        ]
        return jsonify({"session": {"id": s.id, "scenario": sc.name if sc else None}, "results": results})


@ns.route("/sessions/<int:sid>/pdf")
class ExportPDF(Resource):
    @jwt_required()
    def get(self, sid: int):
        s = Session.query.get_or_404(sid)
        sc = Scenario.query.get(s.scenario_id)
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=A4)
        width, height = A4
        
        # Brand colors (customizable)
        primary_color = colors.HexColor(os.getenv('PDF_PRIMARY_COLOR', '#1976d2'))
        secondary_color = colors.HexColor(os.getenv('PDF_SECONDARY_COLOR', '#2e7d32'))
        
        # Cover Page
        c.setFillColor(primary_color)
        c.rect(0, height - 120*mm, width, 120*mm, fill=True, stroke=False)
        
        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 32)
        c.drawCentredString(width/2, height - 60*mm, "Energy Market")
        c.drawCentredString(width/2, height - 70*mm, "Simulation Game")
        
        c.setFont("Helvetica", 18)
        c.drawCentredString(width/2, height - 90*mm, "Session Report")
        
        # Session info box
        c.setFillColor(colors.white)
        c.rect(50, height - 150*mm, width - 100, 40*mm, fill=True, stroke=True)
        
        c.setFillColor(colors.black)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(60, height - 125*mm, f"Session ID: {s.id}")
        c.setFont("Helvetica", 11)
        c.drawString(60, height - 135*mm, f"Scenario: {sc.name if sc else 'N/A'}")
        c.drawString(60, height - 145*mm, f"Status: {s.status.value if s.status else 'N/A'}")
        
        # Footer on cover
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColor(colors.gray)
        c.drawCentredString(width/2, 30*mm, "Generated by EMSG Platform")
        c.drawCentredString(width/2, 25*mm, "© 2025 Energy Market Simulation")
        
        # Logo placeholder (if logo file exists)
        logo_path = os.getenv('PDF_LOGO_PATH', '/app/logo.png')
        if os.path.exists(logo_path):
            try:
                c.drawImage(logo_path, width/2 - 40, height - 180*mm, width=80, height=40, preserveAspectRatio=True)
            except Exception:
                pass  # Skip if logo can't be loaded
        
        c.showPage()
        
        # Page 2: Leaderboard
        def draw_header(page_num):
            c.setFillColor(primary_color)
            c.rect(0, height - 25*mm, width, 20*mm, fill=True, stroke=False)
            c.setFillColor(colors.white)
            c.setFont("Helvetica-Bold", 14)
            c.drawString(50, height - 18*mm, f"EMSG Session {s.id} Report")
            c.setFont("Helvetica", 9)
            c.drawString(width - 80, height - 18*mm, f"Page {page_num}")
            c.setFillColor(colors.black)
        
        page_num = 2
        draw_header(page_num)
        
        # Leaderboard summary
        rows = (
            db.session.query(Result.player_id, Result.data)
            .filter(Result.session_id == sid)
            .all()
        )
        agg = {}
        for pid, data in rows:
            k = data.get("kpis") or {}
            a = agg.setdefault(pid, {"profit_zar": 0, "imbalance_cost_zar": 0, "curtailment_cost_zar": 0, "revenue_zar": 0, "rounds": 0})
            a["profit_zar"] += k.get("profit_zar", 0)
            a["imbalance_cost_zar"] += k.get("imbalance_cost_zar", 0)
            a["curtailment_cost_zar"] += k.get("curtailment_cost_zar", 0)
            a["revenue_zar"] += k.get("revenue_zar", 0)
            a["rounds"] += 1
        lb = [
            {"player_id": pid, **vals} for pid, vals in agg.items()
        ]
        lb.sort(key=lambda x: x["profit_zar"], reverse=True)
        
        y = height - 35*mm
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(secondary_color)
        c.drawString(50, y, "Final Leaderboard")
        y -= 5*mm
        
        # Leaderboard table
        table_data = [["Rank", "Player", "Profit (ZAR)", "Revenue (ZAR)", "Imbalance", "Curtailment"]]
        for idx, row in enumerate(lb[:20], 1):
            table_data.append([
                str(idx),
                f"P{row['player_id']}",
                f"{int(row['profit_zar']):,}",
                f"{int(row['revenue_zar']):,}",
                f"{int(row['imbalance_cost_zar']):,}",
                f"{int(row['curtailment_cost_zar']):,}"
            ])
        
        if len(table_data) > 1:
            t = Table(table_data, colWidths=[30, 50, 80, 80, 80, 80])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ]))
            t.wrapOn(c, width, height)
            t.drawOn(c, 50, y - len(table_data) * 15)
        
        c.showPage()
        
        # Page 3+: Round Details
        page_num = 3
        draw_header(page_num)
        
        y = height - 35*mm
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(secondary_color)
        c.drawString(50, y, "Round-by-Round Details")
        y -= 10*mm
        
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.black)
        for r in Result.query.filter_by(session_id=sid).order_by(Result.round_num, Result.player_id).all():
            k = r.data.get("kpis", {}) if r.data else {}
            line = f"Round {r.round_num} | Player {r.player_id} | SMP: {r.data.get('smp', 'N/A')} | Volume: {r.data.get('volume', 'N/A')} | Profit: {int(k.get('profit_zar', 0)):,} ZAR"
            c.drawString(50, y, line)
            y -= 4*mm
            if y < 30*mm:
                c.showPage()
                page_num += 1
                draw_header(page_num)
                y = height - 35*mm
        
        c.save()
        buf.seek(0)
        return send_file(buf, as_attachment=True, download_name=f"emsg_session_{s.id}.pdf", mimetype="application/pdf")